services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
